# Generated by Django 3.2 on 2021-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='number')),
                ('name', models.CharField(blank=True, max_length=2550, null=True, verbose_name='name')),
                ('temp', models.BooleanField(default=False)),
                ('notes', models.TextField(null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True, verbose_name='q1')),
                ('q2', models.CharField(blank=True, max_length=255, null=True, verbose_name='q2')),
                ('q3', models.CharField(blank=True, max_length=255, null=True, verbose_name='q3')),
                ('q4', models.CharField(blank=True, max_length=255, null=True, verbose_name='q4')),
                ('q5', models.CharField(blank=True, max_length=255, null=True, verbose_name='q5')),
                ('q6', models.CharField(blank=True, max_length=255, null=True, verbose_name='q6')),
                ('q7', models.CharField(blank=True, max_length=255, null=True, verbose_name='q7')),
                ('q8', models.CharField(blank=True, max_length=255, null=True, verbose_name='q8')),
                ('q9', models.CharField(blank=True, max_length=255, null=True, verbose_name='q9')),
                ('q10', models.CharField(blank=True, max_length=255, null=True, verbose_name='q10')),
                ('outcome', models.CharField(blank=True, max_length=20, null=True, verbose_name='outcome')),
                ('date_arose', models.DateField(null=True)),
                ('date_identified', models.DateField(null=True)),
                ('nature', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('why_reportable', models.TextField(blank=True, null=True)),
                ('how_identified', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('representative_details', models.TextField(blank=True, null=True)),
                ('how_rectified', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('future_compliance', models.TextField(blank=True, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('email_code', models.IntegerField(null=True)),
                ('information', models.BooleanField(default=False)),
                ('ho_review', models.BooleanField(default=False)),
                ('ho_reg_affairs_review', models.BooleanField(default=False)),
                ('quality', models.BooleanField(default=False)),
                ('ho_reg_affairs_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='number')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('temp', models.BooleanField(default=False)),
                ('notes', models.TextField(null=True)),
                ('question', models.CharField(blank=True, max_length=1024, null=True, verbose_name='question')),
                ('answer1', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer1')),
                ('answer2', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer2')),
                ('answer3', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer3')),
                ('answer4', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer4')),
                ('answer5', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer5')),
                ('result1', models.CharField(blank=True, max_length=255, null=True, verbose_name='result1')),
                ('result2', models.CharField(blank=True, max_length=255, null=True, verbose_name='result2')),
                ('result3', models.CharField(blank=True, max_length=255, null=True, verbose_name='result3')),
                ('result4', models.CharField(blank=True, max_length=255, null=True, verbose_name='result4')),
                ('result5', models.CharField(blank=True, max_length=255, null=True, verbose_name='result5')),
            ],
        ),
    ]
